apiVersion: batch/v1
kind: Job
metadata:
  name: extract-and-create-secret
  namespace: openshift-logging
  annotations:
    # Job requred hook and cannot use sync-wave alone due to issue about immutable in job manifest. https://github.com/argoproj/argo-cd/discussions/7984
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: oc-command-job
        image: registry.redhat.io/openshift4/ose-cli # Ensure this image has the oc CLI
        command:
        - /bin/bash
        - -c
        args:
        - |
          OB_NAME="obc-openshift-logging-obc-loki-bucket";
          OBC_NAME="obc-loki-bucket";
          LOKI_SEC="loki-sec-obj"
          BUCKET_ACCESS_ID="$(oc get secret -n openshift-logging $OBC_NAME -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)";
          BUCKET_ACCESS_KEY="$(oc get secret -n openshift-logging $OBC_NAME -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)";
          BUCKET_NAME=$(oc get ob $OB_NAME -n openshift-logging -o jsonpath='{.spec.endpoint.bucketName}');
          BUCKET_ENDPOINT=$(oc get ob $OB_NAME -n openshift-logging -o jsonpath='{.spec.endpoint.bucketHost}');
          oc create secret generic $LOKI_SEC --from-literal=bucketnames="$BUCKET_NAME" --from-literal=endpoint="https://$BUCKET_ENDPOINT:443" --from-literal=access_key_id="$BUCKET_ACCESS_ID" --from-literal=access_key_secret="$BUCKET_ACCESS_KEY" -n openshift-logging --dry-run=client -o yaml > secret.yaml;
          oc apply -f secret.yaml
      serviceAccountName: "gitops-sa"
      serviceAccount: "gitops-sa"
      restartPolicy: Never
  backoffLimit: 3
