apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-loki-bucket
  namespace: openshift-logging
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: loki-bucket
  generateBucketName: loki-bucket
  objectBucketName: obc-loki-bucket
  storageClassName: openshift-storage.noobaa.io
